export const EVENTS = [
  {
    id: 1,
    title: "International Conference on Quantum Computing & Information Theory",
    description: "A two-day international conference featuring keynote speakers from MIT, IISc, and CERN. Topics include quantum error correction, quantum algorithms, and quantum machine learning applications.",
    type: "conference",
    department: "Dept. of Physics",
    faculty: "Faculty of Science",
    date: "2026-05-01",
    endDate: "2026-05-02",
    time: "09:00 AM - 05:00 PM",
    venue: "Swatantrata Bhawan Auditorium",
    speaker: "Prof. Arun Kumar, Dr. Sarah Chen (MIT)",
    organizer: "Prof. Rajesh Verma",
    registrations: 342,
    capacity: 500,
    tags: ["quantum computing", "physics", "research", "international"],
    featured: true,
    status: "approved",
    image: null,
    color: "#f43f5e"
  },
  {
    id: 2,
    title: "Workshop on Deep Learning for Natural Language Processing",
    description: "Hands-on workshop covering transformer architectures, BERT, GPT models, and their applications in Indian language processing. Participants will build a sentiment analysis model.",
    type: "workshop",
    department: "Dept. of Computer Science",
    faculty: "Institute of Technology",
    date: "2026-05-03",
    endDate: "2026-05-03",
    time: "10:00 AM - 04:00 PM",
    venue: "IT-BHU Computer Lab 3",
    speaker: "Dr. Priya Sharma",
    organizer: "Dr. Priya Sharma",
    registrations: 89,
    capacity: 100,
    tags: ["deep learning", "NLP", "AI", "workshop"],
    featured: true,
    status: "approved",
    image: null,
    color: "#f59e0b"
  },
  {
    id: 3,
    title: "Guest Lecture: Climate Change and Sustainable Agriculture",
    description: "Distinguished lecture by IARI Director on the impact of climate change on agricultural patterns in the Indo-Gangetic plain and sustainable farming techniques.",
    type: "lecture",
    department: "Dept. of Agricultural Sciences",
    faculty: "Faculty of Agriculture",
    date: "2026-05-04",
    endDate: "2026-05-04",
    time: "03:00 PM - 05:00 PM",
    venue: "Rajiv Gandhi South Campus Auditorium",
    speaker: "Dr. Trilochan Mohapatra (Director, IARI)",
    organizer: "Prof. Sunita Devi",
    registrations: 156,
    capacity: 300,
    tags: ["agriculture", "climate change", "sustainability", "guest lecture"],
    featured: false,
    status: "approved",
    image: null,
    color: "#10b981"
  },
  {
    id: 4,
    title: "Seminar on Ancient Indian Mathematical Traditions",
    description: "Exploring the mathematical contributions of Aryabhata, Brahmagupta, and the Kerala School. How ancient Indian mathematics influenced modern computational methods.",
    type: "seminar",
    department: "Dept. of Mathematics",
    faculty: "Faculty of Science",
    date: "2026-05-05",
    endDate: "2026-05-05",
    time: "11:00 AM - 01:00 PM",
    venue: "Science Faculty Hall",
    speaker: "Prof. K. Ramasubramanian (IIT Bombay)",
    organizer: "Dr. Anand Mishra",
    registrations: 78,
    capacity: 150,
    tags: ["mathematics", "history", "seminar", "Indian heritage"],
    featured: false,
    status: "approved",
    image: null,
    color: "#6366f1"
  },
  {
    id: 5,
    title: "Training Program: Research Methodology & Scientific Writing",
    description: "Five-day training program for research scholars covering research design, statistical analysis using R and Python, literature review techniques, and writing for high-impact journals.",
    type: "training",
    department: "Central Library",
    faculty: "University Administration",
    date: "2026-05-06",
    endDate: "2026-05-07",
    time: "09:30 AM - 03:30 PM",
    venue: "Central Library Seminar Hall",
    speaker: "Multiple Faculty Members",
    organizer: "Chief Librarian Dr. Meena Gupta",
    registrations: 210,
    capacity: 250,
    tags: ["research", "training", "scientific writing", "methodology"],
    featured: true,
    status: "approved",
    image: null,
    color: "#06b6d4"
  },
  {
    id: 6,
    title: "National Symposium on Ayurvedic Pharmacology",
    description: "Two-day national symposium on recent advances in Ayurvedic drug development, clinical trials methodology for traditional medicine, and integration with modern pharmacology.",
    type: "conference",
    department: "Faculty of Ayurveda",
    faculty: "Faculty of Ayurveda",
    date: "2026-05-08",
    endDate: "2026-05-09",
    time: "10:00 AM - 05:00 PM",
    venue: "Ayurveda Campus Auditorium",
    speaker: "Vaidya Rajesh Kotecha (Secretary, Ministry of AYUSH)",
    organizer: "Prof. Yamini Bhushan Tripathi",
    registrations: 180,
    capacity: 400,
    tags: ["ayurveda", "pharmacology", "traditional medicine", "national"],
    featured: false,
    status: "approved",
    image: null,
    color: "#f43f5e"
  },
  {
    id: 7,
    title: "Workshop on Drone Technology for Civil Engineering",
    description: "Practical workshop on using drone survey technology for civil engineering projects including photogrammetry, LIDAR mapping, and structural health monitoring.",
    type: "workshop",
    department: "Dept. of Civil Engineering",
    faculty: "Institute of Technology",
    date: "2026-05-10",
    endDate: "2026-05-10",
    time: "09:00 AM - 04:00 PM",
    venue: "Civil Engineering Labs, IIT-BHU",
    speaker: "Dr. Vikram Singh, Skylark Technologies",
    organizer: "Prof. Amit Kumar",
    registrations: 45,
    capacity: 60,
    tags: ["drones", "civil engineering", "technology", "hands-on"],
    featured: false,
    status: "approved",
    image: null,
    color: "#f59e0b"
  },
  {
    id: 8,
    title: "Guest Lecture: Decoding the Human Brain — Neuroscience Frontiers",
    description: "Cutting-edge lecture on brain-computer interfaces, neural mapping projects, and the future of neuroscience research in India.",
    type: "lecture",
    department: "Dept. of Zoology",
    faculty: "Faculty of Science",
    date: "2026-05-11",
    endDate: "2026-05-11",
    time: "02:00 PM - 04:00 PM",
    venue: "Mahila Mahavidyalaya Lecture Hall",
    speaker: "Dr. Nandini Chatterjee Singh (UNESCO MGIEP)",
    organizer: "Dr. Ravi Shankar",
    registrations: 134,
    capacity: 200,
    tags: ["neuroscience", "brain", "biology", "guest lecture"],
    featured: false,
    status: "approved",
    image: null,
    color: "#10b981"
  },
  {
    id: 9,
    title: "Hackathon: Smart Campus Solutions",
    description: "24-hour hackathon challenging students to build innovative solutions for campus problems — smart attendance, energy monitoring, waste management, and campus navigation.",
    type: "workshop",
    department: "Dept. of Computer Science",
    faculty: "Institute of Technology",
    date: "2026-05-12",
    endDate: "2026-05-13",
    time: "10:00 AM (Sat) - 10:00 AM (Sun)",
    venue: "IT-BHU Seminar Hall",
    speaker: "Industry Mentors from Google, Microsoft",
    organizer: "Coding Club, IIT-BHU",
    registrations: 256,
    capacity: 300,
    tags: ["hackathon", "coding", "innovation", "smart campus"],
    featured: true,
    status: "approved",
    image: null,
    color: "#f59e0b"
  },
  {
    id: 10,
    title: "Seminar on Sanskrit Computational Linguistics",
    description: "Interdisciplinary seminar exploring the intersection of Sanskrit grammar (Paninian framework) and modern computational linguistics, NLP, and AI.",
    type: "seminar",
    department: "Dept. of Sanskrit",
    faculty: "Faculty of Arts",
    date: "2026-05-13",
    endDate: "2026-05-13",
    time: "11:00 AM - 01:30 PM",
    venue: "Arts Faculty Seminar Room",
    speaker: "Prof. Amba Kulkarni (Univ. of Hyderabad)",
    organizer: "Prof. Shrinivasa Varakhedi",
    registrations: 67,
    capacity: 120,
    tags: ["sanskrit", "computational linguistics", "NLP", "interdisciplinary"],
    featured: false,
    status: "approved",
    image: null,
    color: "#6366f1"
  },
  {
    id: 11,
    title: "Panel Discussion: Women in STEM — Breaking Barriers",
    description: "Panel featuring distinguished women scientists and engineers discussing challenges, opportunities, and mentorship for women pursuing careers in STEM fields.",
    type: "seminar",
    department: "Women's Studies Centre",
    faculty: "University Administration",
    date: "2026-05-14",
    endDate: "2026-05-14",
    time: "03:00 PM - 05:30 PM",
    venue: "Convention Hall, BHU Main Campus",
    speaker: "Dr. Tessy Thomas (DRDO), Prof. Rohini Godbole (IISc)",
    organizer: "Dr. Archana Singh",
    registrations: 198,
    capacity: 350,
    tags: ["women in STEM", "panel discussion", "diversity", "career"],
    featured: true,
    status: "approved",
    image: null,
    color: "#8b5cf6"
  },
  {
    id: 12,
    title: "Training: LaTeX & Academic Publishing Tools",
    description: "Hands-on training on LaTeX document preparation, BibTeX references, Overleaf collaboration, and journal submission workflows for research scholars.",
    type: "training",
    department: "Dept. of Computer Science",
    faculty: "Institute of Technology",
    date: "2026-05-15",
    endDate: "2026-05-15",
    time: "10:00 AM - 03:00 PM",
    venue: "Computer Centre, BHU",
    speaker: "Dr. Mohit Kumar",
    organizer: "Dr. Mohit Kumar",
    registrations: 95,
    capacity: 120,
    tags: ["LaTeX", "publishing", "training", "research tools"],
    featured: false,
    status: "approved",
    image: null,
    color: "#06b6d4"
  }
];

export const DEPARTMENTS = [
  "All Departments",
  "Dept. of Physics",
  "Dept. of Chemistry",
  "Dept. of History",
  "Dept. of Computer Science",
  "Dept. of Electrical and Electronics Engineering",
  "Dept. of Mathematics",
  "Dept. of Agricultural Sciences",
  "Dept. of Civil Engineering",
  "Dept. of Zoology",
  "Dept. of Sanskrit",
  "Faculty of Ayurveda",
  "Women's Studies Centre",
  "Central Library"
];

export const EVENT_TYPES = [
  { value: "all", label: "All Types", color: "#6366f1" },
  { value: "seminar", label: "Seminar", color: "#6366f1" },
  { value: "workshop", label: "Workshop", color: "#f59e0b" },
  { value: "conference", label: "Conference", color: "#f43f5e" },
  { value: "lecture", label: "Guest Lecture", color: "#10b981" },
  { value: "training", label: "Training", color: "#06b6d4" }
];

export const FEATURES = [
  {
    icon: "🔍",
    title: "Smart Discovery",
    description: "AI-powered recommendations based on your department, research interests, and past event attendance.",
    gradient: "linear-gradient(135deg, rgba(99,102,241,0.2), rgba(99,102,241,0.05))"
  },
  {
    icon: "🔔",
    title: "Instant Notifications",
    description: "Get real-time alerts for events matching your interests. Never miss a relevant seminar or workshop again.",
    gradient: "linear-gradient(135deg, rgba(245,158,11,0.2), rgba(245,158,11,0.05))"
  },
  {
    icon: "📅",
    title: "Calendar Integration",
    description: "Sync events to Google Calendar or export ICS files. View all campus events in a unified calendar view.",
    gradient: "linear-gradient(135deg, rgba(16,185,129,0.2), rgba(16,185,129,0.05))"
  },
  {
    icon: "📊",
    title: "Analytics Dashboard",
    description: "Track event reach, registrations, and attendance. Data-driven insights for better event planning.",
    gradient: "linear-gradient(135deg, rgba(244,63,94,0.2), rgba(244,63,94,0.05))"
  },

  {
    icon: "🏛️",
    title: "Cross-Department Discovery",
    description: "Break departmental silos. Discover events from every faculty and department across the university.",
    gradient: "linear-gradient(135deg, rgba(6,182,212,0.2), rgba(6,182,212,0.05))"
  }
];
